# Site wide configuration

title:            Renaud Gervais
locale:           en_US
# url:
url:              http://renaudgervais.github.io


# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Renaud Gervais
  avatar: bio-photo-2.jpg
  bio: "Researcher, designer, programmer. I like tinkering with ideas that lie at the boundaries of different fields."
  email: renaud.gervais@gmail.com
  disqus-shortname:
  twitter: RenaudGervais #username
  facebook: #username
  google:
    plus: RenaudGervais-1 #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: RenaudGervais #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: renaud-gervais/27/7b6/338 #username
  xing: #username
  instagram: #username
  lastfm: NonRealResult #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]


# Jekyll-scholar config
scholar:
  style: chicago-annotated-bibliography
  locale: en

  sort_by: year
  order: reverse

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: bib # References the template ./_layouts/bib.html

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  repository: ./papers

  query: "@*"
