title:            Renaud Gervais
description:      Describe your website.
# Your site's domain goes here. Leave localhost server or blank when working locally.
# url:              
url:              http://renaudgervais.github.io
disqus_shortname:

# Owner/author information
owner:
  name:           Renaud Gervais
  avatar:         bio-photo.jpg
  bio:            "Researcher, designer, programmer. I like tinkering with ideas that lie at the boundaries of different fields."
#  Particularly interested in tangible interfaces, spatial augmented reality, ubiquitous computing and creative coding."
  email:          renaud.gervais@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:			RenaudGervais
  facebook:
  github:			RenaudGervais
  stackoverflow:
  linkedin:			renaud-gervais/27/7b6/338
  instagram:
  lastfm:			NonRealResult
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:		RenaudGervais-1

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  # - title: Blog
  #   url: /posts/
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Publications
    url: /publications/
  - title: About
    url: /about/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

encoding: utf-8

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]


# Jekyll-scholar config
scholar:
  style: chicago-annotated-bibliography
  locale: en

  sort_by: year
  order: reverse

  source: ./_bibliography
  bibliography: publications.bib
  bibliography_template: bib # References the template ./_layouts/bib.html

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  repository: ./papers

  query: "@*"
